# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.server_options_sizes import ServerOptionsSizes

class TestServerOptionsSizes(unittest.TestCase):
    """ServerOptionsSizes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerOptionsSizes:
        """Test ServerOptionsSizes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerOptionsSizes`
        """
        model = ServerOptionsSizes()
        if include_optional:
            return ServerOptionsSizes(
                sizes = {
                    'key' : null
                    }
            )
        else:
            return ServerOptionsSizes(
        )
        """

    def testServerOptionsSizes(self):
        """Test ServerOptionsSizes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
