# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.depoloyments_list import DepoloymentsList

class TestDepoloymentsList(unittest.TestCase):
    """DepoloymentsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepoloymentsList:
        """Test DepoloymentsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepoloymentsList`
        """
        model = DepoloymentsList()
        if include_optional:
            return DepoloymentsList(
                deployments = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return DepoloymentsList(
        )
        """

    def testDepoloymentsList(self):
        """Test DepoloymentsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
