# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.notification_subscription_delete import NotificationSubscriptionDelete

class TestNotificationSubscriptionDelete(unittest.TestCase):
    """NotificationSubscriptionDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationSubscriptionDelete:
        """Test NotificationSubscriptionDelete
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationSubscriptionDelete`
        """
        model = NotificationSubscriptionDelete()
        if include_optional:
            return NotificationSubscriptionDelete(
                user_id = '',
                topic = ''
            )
        else:
            return NotificationSubscriptionDelete(
                topic = '',
        )
        """

    def testNotificationSubscriptionDelete(self):
        """Test NotificationSubscriptionDelete"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
