# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.viewer import Viewer

class TestViewer(unittest.TestCase):
    """Viewer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Viewer:
        """Test Viewer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Viewer`
        """
        model = Viewer()
        if include_optional:
            return Viewer(
                user_id = '',
                group_id = '',
                route_id = '',
                id = '',
                created_at = '',
                name = '',
                avatar_url = ''
            )
        else:
            return Viewer(
                name = '',
                avatar_url = '',
        )
        """

    def testViewer(self):
        """Test Viewer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
