# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.workspace import Workspace

class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Workspace:
        """Test Workspace
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Workspace`
        """
        model = Workspace()
        if include_optional:
            return Workspace(
                owner_id = '',
                owner_name = ERROR_TO_EXAMPLE_VALUE,
                user_id = '',
                group_id = '',
                org_id = '',
                owner = saturn_api.models.owner.Owner(
                    id = '', 
                    name = '', 
                    identity_name = '', 
                    created_at = '', 
                    org_admin = True, 
                    org_id = '', 
                    user_id = '', 
                    group_id = '', 
                    identity_type = '', 
                    limits_id = '', 
                    avatar_url = '', 
                    is_multiple_ssh_keys = True, ),
                name = '',
                image = '',
                image_tag_id = '',
                image_enforce_trusted = True,
                extra_packages = saturn_api.models.extra_packages.ExtraPackages(
                    pip = '', 
                    conda = '', 
                    as_environment_yml = True, 
                    as_requirements_txt = True, 
                    apt = '', 
                    cran = '', 
                    remotes = '', 
                    bioconductor = '', 
                    use_mamba = True, ),
                ide = '',
                start_script = '',
                environment_variables = {
                    'key' : ''
                    },
                working_dir = '',
                description = '',
                disk_space = '',
                instance_size = '',
                auto_shutoff = '',
                start_ssh = True,
                is_spot = True,
                subdomain = '',
                start_dind = True,
                external_repo_attachments = [
                    saturn_api.models.external_repo_attachment_partial.ExternalRepoAttachmentPartial(
                        id = '', 
                        has_sshkey = True, 
                        path = '', 
                        created_at = '', 
                        external_repo_id = '', 
                        remote_url = '', 
                        on_restart = 'preserve changes', 
                        ref = '', 
                        ref_type = 'branch', )
                    ],
                id = '',
                image_tag = saturn_api.models.resource_image_tag.ResourceImageTag(
                    id = '', 
                    version = '', 
                    image_uri = '', 
                    image = null, ),
                resource_type = '',
                size_display = '',
                k8s_name = '',
                require_restart = True,
                created_at = '',
                updated_at = '',
                started_at = '',
                self_destruct = True
            )
        else:
            return Workspace(
                name = '',
        )
        """

    def testWorkspace(self):
        """Test Workspace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
