# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.instance_size import InstanceSize

class TestInstanceSize(unittest.TestCase):
    """InstanceSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceSize:
        """Test InstanceSize
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceSize`
        """
        model = InstanceSize()
        if include_optional:
            return InstanceSize(
                name = '',
                cores = 56,
                memory = '',
                gpu = 56,
                cloud = '',
                display = '',
                display_name = '',
                node_role = '',
                reserved_memory = '512Mi',
                reserved_cpu = 1.337
            )
        else:
            return InstanceSize(
                name = '',
                cores = 56,
                memory = '',
        )
        """

    def testInstanceSize(self):
        """Test InstanceSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
