# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.dask_cluster import DaskCluster

class TestDaskCluster(unittest.TestCase):
    """DaskCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DaskCluster:
        """Test DaskCluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DaskCluster`
        """
        model = DaskCluster()
        if include_optional:
            return DaskCluster(
                id = '',
                name = '',
                owner = saturn_api.models.owner.Owner(
                    id = '', 
                    name = '', 
                    identity_name = '', 
                    created_at = '', 
                    org_admin = True, 
                    org_id = '', 
                    user_id = '', 
                    group_id = '', 
                    identity_type = '', 
                    limits_id = '', 
                    avatar_url = '', 
                    is_multiple_ssh_keys = True, ),
                resource_type = '',
                workspace = ERROR_TO_EXAMPLE_VALUE,
                deployment = ERROR_TO_EXAMPLE_VALUE,
                worker_size = '',
                worker_size_display = '',
                worker_is_spot = True,
                scheduler_size = '',
                scheduler_size_display = '',
                n_workers = 56,
                nprocs = 56,
                nthreads = 56,
                deployment_id = '',
                workspace_id = '',
                scheduler_url = '',
                subdomain = '',
                url = '',
                image = '',
                created_at = ''
            )
        else:
            return DaskCluster(
                id = '',
                name = '',
                owner = saturn_api.models.owner.Owner(
                    id = '', 
                    name = '', 
                    identity_name = '', 
                    created_at = '', 
                    org_admin = True, 
                    org_id = '', 
                    user_id = '', 
                    group_id = '', 
                    identity_type = '', 
                    limits_id = '', 
                    avatar_url = '', 
                    is_multiple_ssh_keys = True, ),
                resource_type = '',
                worker_size = '',
                worker_size_display = '',
                worker_is_spot = True,
                scheduler_size = '',
                scheduler_size_display = '',
                n_workers = 56,
                nprocs = 56,
                nthreads = 56,
                scheduler_url = '',
                subdomain = '',
                url = '',
                image = '',
                created_at = '',
        )
        """

    def testDaskCluster(self):
        """Test DaskCluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
