# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.resource_template import ResourceTemplate

class TestResourceTemplate(unittest.TestCase):
    """ResourceTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceTemplate:
        """Test ResourceTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceTemplate`
        """
        model = ResourceTemplate()
        if include_optional:
            return ResourceTemplate(
                owner_id = '',
                owner_name = ERROR_TO_EXAMPLE_VALUE,
                user_id = '',
                group_id = '',
                org_id = '',
                owner = saturn_api.models.owner.Owner(
                    id = '', 
                    name = '', 
                    identity_name = '', 
                    created_at = '', 
                    org_admin = True, 
                    org_id = '', 
                    user_id = '', 
                    group_id = '', 
                    identity_type = '', 
                    limits_id = '', 
                    avatar_url = '', 
                    is_multiple_ssh_keys = True, ),
                name = '0',
                description = '',
                thumbnail_image_url = '',
                weight = 56,
                recipe = {
                    'key' : null
                    },
                access = 'account',
                id = '',
                editable = None,
                created_at = ''
            )
        else:
            return ResourceTemplate(
                name = '0',
                description = '',
                recipe = {
                    'key' : null
                    },
        )
        """

    def testResourceTemplate(self):
        """Test ResourceTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
