# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.image_tag import ImageTag

class TestImageTag(unittest.TestCase):
    """ImageTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageTag:
        """Test ImageTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageTag`
        """
        model = ImageTag()
        if include_optional:
            return ImageTag(
                id = '',
                created_at = '',
                image = ERROR_TO_EXAMPLE_VALUE,
                image_uri = '',
                description = '',
                version = '0',
                build_data = saturn_api.models.build_data.BuildData(
                    base_image = '', 
                    environment_yml = '', 
                    requirements_txt = '', 
                    cran_packages = '', 
                    bioconductor_packages = '', 
                    remotes_packages = '', 
                    apt_txt = '', 
                    post_build = '', 
                    use_mamba = True, 
                    adapt_image = True, 
                    register_ipython_kernel = True, 
                    rstudio_version = '', 
                    install_r = True, ),
                archived = True,
                is_external = True,
                status = '',
                saturn_env = '',
                resource_type = '',
                editable = True
            )
        else:
            return ImageTag(
                version = '0',
        )
        """

    def testImageTag(self):
        """Test ImageTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
