# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.container_runtime_summary import ContainerRuntimeSummary

class TestContainerRuntimeSummary(unittest.TestCase):
    """ContainerRuntimeSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerRuntimeSummary:
        """Test ContainerRuntimeSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerRuntimeSummary`
        """
        model = ContainerRuntimeSummary()
        if include_optional:
            return ContainerRuntimeSummary(
                name = '',
                namespace = '',
                uid = '',
                controller_uid = '',
                controller_kind = '',
                labels = {
                    'key' : ''
                    },
                annotations = {
                    'key' : ''
                    },
                conditions = [
                    saturn_api.models.condition.Condition(
                        type = '', 
                        status = '', 
                        reason = '', 
                        message = '', 
                        last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_probe_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'waiting',
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                restart_policy = 'Always',
                image_pulled = True,
                exit_code = 56,
                logs = '',
                reason = 'Evicted',
                ready = True,
                is_previous = True,
                previous = saturn_api.models.container_runtime_summary.ContainerRuntimeSummary(
                    name = '', 
                    namespace = '', 
                    uid = '', 
                    controller_uid = '', 
                    controller_kind = '', 
                    labels = {
                        'key' : ''
                        }, 
                    annotations = {
                        'key' : ''
                        }, 
                    conditions = [
                        saturn_api.models.condition.Condition(
                            type = '', 
                            status = '', 
                            reason = '', 
                            message = '', 
                            last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_probe_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = 'waiting', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    restart_policy = 'Always', 
                    image_pulled = True, 
                    exit_code = 56, 
                    logs = '', 
                    reason = 'Evicted', 
                    ready = True, 
                    is_previous = True, 
                    previous = null, )
            )
        else:
            return ContainerRuntimeSummary(
                name = '',
                namespace = '',
                uid = '',
        )
        """

    def testContainerRuntimeSummary(self):
        """Test ContainerRuntimeSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
