# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saturn_api.models.notification_list import NotificationList

class TestNotificationList(unittest.TestCase):
    """NotificationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationList:
        """Test NotificationList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationList`
        """
        model = NotificationList()
        if include_optional:
            return NotificationList(
                notifications = [
                    saturn_api.models.notification.Notification(
                        id = '', 
                        user_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        topic = '', 
                        message = '', 
                        data = {
                            'key' : null
                            }, 
                        acknowledged = True, )
                    ],
                prev_key = '',
                next_key = ''
            )
        else:
            return NotificationList(
                notifications = [
                    saturn_api.models.notification.Notification(
                        id = '', 
                        user_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        topic = '', 
                        message = '', 
                        data = {
                            'key' : null
                            }, 
                        acknowledged = True, )
                    ],
        )
        """

    def testNotificationList(self):
        """Test NotificationList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
