# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from saturn_api.models.artifact_kind import ArtifactKind
from saturn_api.models.artifact_status import ArtifactStatus


class ArtifactCreate(BaseModel):
    """
    ArtifactCreate
    """  # noqa: E501

    name: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="Human-readable name for the artifact."
    )
    kind: Optional[ArtifactKind] = None
    location: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="Storage location (NFS path or object storage URI)."
    )
    status: Optional[ArtifactStatus] = None
    producer: Optional[Dict[str, Any]] = Field(
        default=None,
        description="JSONB snapshot of the Saturn resource that produced this artifact. Shape: {id, kind, name}. Null if uploaded directly.",
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Arbitrary metadata blob: schema_type, row_count, base_model, epoch, metrics, etc.",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "kind",
        "location",
        "status",
        "producer",
        "metadata",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArtifactCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if producer (nullable) is None
        # and model_fields_set contains the field
        if self.producer is None and "producer" in self.model_fields_set:
            _dict["producer"] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict["metadata"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArtifactCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "kind": obj.get("kind"),
                "location": obj.get("location"),
                "status": obj.get("status"),
                "producer": obj.get("producer"),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
