# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from saturn_api.models.cluster_connection_type import ClusterConnectionType


class ClusterCreate(BaseModel):
    """
    ClusterCreate
    """  # noqa: E501

    name: StrictStr = Field(description="Unique name of the cluster.")
    org_id: StrictStr = Field(description="ID of the org that owns the cluster.")
    connection_type: ClusterConnectionType
    server_url: Optional[StrictStr] = Field(
        default=None, description="K8s API server URL. Required when connection_type is 'token'."
    )
    ca_bundle: Optional[StrictStr] = Field(
        default=None,
        description="Base64-encoded CA bundle. Required when connection_type is 'token'.",
    )
    token: Optional[StrictStr] = Field(
        default=None,
        description="Bearer token for k8s API. Required when connection_type is 'token'.",
    )
    utilities: Optional[Dict[str, Any]] = Field(
        default=None, description="ClusterUtilities metadata (service endpoints)."
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "org_id",
        "connection_type",
        "server_url",
        "ca_bundle",
        "token",
        "utilities",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if server_url (nullable) is None
        # and model_fields_set contains the field
        if self.server_url is None and "server_url" in self.model_fields_set:
            _dict["server_url"] = None

        # set to None if ca_bundle (nullable) is None
        # and model_fields_set contains the field
        if self.ca_bundle is None and "ca_bundle" in self.model_fields_set:
            _dict["ca_bundle"] = None

        # set to None if token (nullable) is None
        # and model_fields_set contains the field
        if self.token is None and "token" in self.model_fields_set:
            _dict["token"] = None

        # set to None if utilities (nullable) is None
        # and model_fields_set contains the field
        if self.utilities is None and "utilities" in self.model_fields_set:
            _dict["utilities"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "org_id": obj.get("org_id"),
                "connection_type": obj.get("connection_type"),
                "server_url": obj.get("server_url"),
                "ca_bundle": obj.get("ca_bundle"),
                "token": obj.get("token"),
                "utilities": obj.get("utilities"),
            }
        )
        return _obj
