# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from saturn_api.models.cluster_connection_type import ClusterConnectionType


class Cluster(BaseModel):
    """
    Cluster
    """  # noqa: E501

    id: StrictStr = Field(description="Cluster ID.")
    name: StrictStr = Field(description="Cluster name.")
    org_id: StrictStr = Field(description="Owning org ID.")
    connection_type: ClusterConnectionType
    server_url: Optional[StrictStr] = Field(default=None, description="K8s API server URL.")
    utilities: Optional[Dict[str, Any]] = Field(
        default=None, description="ClusterUtilities metadata."
    )
    created_at: StrictStr = Field(description="Creation timestamp.")
    updated_at: StrictStr = Field(description="Last update timestamp.")
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "org_id",
        "connection_type",
        "server_url",
        "utilities",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "name",
                "org_id",
                "server_url",
                "utilities",
                "created_at",
                "updated_at",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if server_url (nullable) is None
        # and model_fields_set contains the field
        if self.server_url is None and "server_url" in self.model_fields_set:
            _dict["server_url"] = None

        # set to None if utilities (nullable) is None
        # and model_fields_set contains the field
        if self.utilities is None and "utilities" in self.model_fields_set:
            _dict["utilities"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "org_id": obj.get("org_id"),
                "connection_type": obj.get("connection_type"),
                "server_url": obj.get("server_url"),
                "utilities": obj.get("utilities"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
