# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictStr
from typing_extensions import Self


class Condition(BaseModel):
    """
    Condition
    """  # noqa: E501

    type: StrictStr
    status: StrictStr
    reason: Optional[StrictStr]
    message: Optional[StrictStr]
    last_transition_time: Optional[datetime]
    last_probe_time: Optional[datetime]
    __properties: ClassVar[List[str]] = [
        "type",
        "status",
        "reason",
        "message",
        "last_transition_time",
        "last_probe_time",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Condition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "type",
                "status",
                "reason",
                "message",
                "last_transition_time",
                "last_probe_time",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict["reason"] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict["message"] = None

        # set to None if last_transition_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_transition_time is None and "last_transition_time" in self.model_fields_set:
            _dict["last_transition_time"] = None

        # set to None if last_probe_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_probe_time is None and "last_probe_time" in self.model_fields_set:
            _dict["last_probe_time"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Condition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "type": obj.get("type"),
                "status": obj.get("status"),
                "reason": obj.get("reason"),
                "message": obj.get("message"),
                "last_transition_time": obj.get("last_transition_time"),
                "last_probe_time": obj.get("last_probe_time"),
            }
        )
        return _obj
