# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class DailyUsage(BaseModel):
    """
    DailyUsage
    """  # noqa: E501

    hours: Union[StrictFloat, StrictInt] = Field(description="Compute hours used.")
    dollars: Union[StrictFloat, StrictInt] = Field(description="Dollars spent.")
    var_date: date = Field(description="Date of the usage record.", alias="date")
    instance_type: StrictStr = Field(description="Instance type used.")
    resource_type: StrictStr = Field(description="Resource type used.")
    __properties: ClassVar[List[str]] = [
        "hours",
        "dollars",
        "date",
        "instance_type",
        "resource_type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DailyUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DailyUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "hours": obj.get("hours"),
                "dollars": obj.get("dollars"),
                "date": obj.get("date"),
                "instance_type": obj.get("instance_type"),
                "resource_type": obj.get("resource_type"),
            }
        )
        return _obj
