# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from saturn_api.models.resource_reference import ResourceReference


class DaskClusterCreate(BaseModel):
    """
    DaskClusterCreate
    """  # noqa: E501

    resource: ResourceReference
    tags: Optional[Dict[str, StrictStr]] = None
    worker_size: Optional[StrictStr] = None
    worker_is_spot: Optional[StrictBool] = False
    scheduler_size: Optional[StrictStr] = None
    n_workers: Optional[StrictInt] = 1
    nthreads: Optional[StrictInt] = 2
    nprocs: Optional[StrictInt] = None
    subdomain: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "resource",
        "tags",
        "worker_size",
        "worker_is_spot",
        "scheduler_size",
        "n_workers",
        "nthreads",
        "nprocs",
        "subdomain",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DaskClusterCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resource
        if self.resource:
            _dict["resource"] = self.resource.to_dict()
        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if subdomain (nullable) is None
        # and model_fields_set contains the field
        if self.subdomain is None and "subdomain" in self.model_fields_set:
            _dict["subdomain"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DaskClusterCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "resource": (
                    ResourceReference.from_dict(obj["resource"])
                    if obj.get("resource") is not None
                    else None
                ),
                "tags": obj.get("tags"),
                "worker_size": obj.get("worker_size"),
                "worker_is_spot": (
                    obj.get("worker_is_spot") if obj.get("worker_is_spot") is not None else False
                ),
                "scheduler_size": obj.get("scheduler_size"),
                "n_workers": obj.get("n_workers") if obj.get("n_workers") is not None else 1,
                "nthreads": obj.get("nthreads") if obj.get("nthreads") is not None else 2,
                "nprocs": obj.get("nprocs"),
                "subdomain": obj.get("subdomain"),
            }
        )
        return _obj
