# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from saturn_api.models.default_images import DefaultImages
from saturn_api.models.default_sizes import DefaultSizes
from saturn_api.models.server_options_size import ServerOptionsSize


class DeploymentServerInfo(BaseModel):
    """
    DeploymentServerInfo
    """  # noqa: E501

    server_options: ServerOptionsSize = Field(description="Configuration options for deployments.")
    default_images: DefaultImages = Field(description="Default images for deployments.")
    default_sizes: DefaultSizes = Field(description="Default instance sizes for deployments.")
    __properties: ClassVar[List[str]] = ["server_options", "default_images", "default_sizes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeploymentServerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of server_options
        if self.server_options:
            _dict["server_options"] = self.server_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_images
        if self.default_images:
            _dict["default_images"] = self.default_images.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_sizes
        if self.default_sizes:
            _dict["default_sizes"] = self.default_sizes.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentServerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "server_options": (
                    ServerOptionsSize.from_dict(obj["server_options"])
                    if obj.get("server_options") is not None
                    else None
                ),
                "default_images": (
                    DefaultImages.from_dict(obj["default_images"])
                    if obj.get("default_images") is not None
                    else None
                ),
                "default_sizes": (
                    DefaultSizes.from_dict(obj["default_sizes"])
                    if obj.get("default_sizes") is not None
                    else None
                ),
            }
        )
        return _obj
