# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.06.01-36
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from saturn_api.models.owner import Owner
from saturn_api.models.ssh_private_key_partial import SSHPrivateKeyPartial
from typing import Literal, Optional, Set
from typing_extensions import Self

class ExternalRepo(BaseModel):
    """
    ExternalRepo
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    owner: Owner
    created_at: StrictStr
    remote_url: StrictStr
    ssh_privatekey_id: Optional[StrictStr] = None
    ssh_privatekey: Optional[SSHPrivateKeyPartial] = None
    __properties: ClassVar[List[str]] = ["id", "name", "owner", "created_at", "remote_url", "ssh_privatekey_id", "ssh_privatekey"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalRepo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "name",
            "owner",
            "created_at",
            "remote_url",
            "ssh_privatekey_id",
            "ssh_privatekey",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ssh_privatekey
        if self.ssh_privatekey:
            _dict['ssh_privatekey'] = self.ssh_privatekey.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalRepo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "owner": Owner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "created_at": obj.get("created_at"),
            "remote_url": obj.get("remote_url"),
            "ssh_privatekey_id": obj.get("ssh_privatekey_id"),
            "ssh_privatekey": SSHPrivateKeyPartial.from_dict(obj["ssh_privatekey"]) if obj.get("ssh_privatekey") is not None else None
        })
        return _obj


