# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2026.02.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Literal, Optional, Set
from typing_extensions import Self

class ExternalRepoAttachmentRecipe(BaseModel):
    """
    ExternalRepoAttachmentRecipe
    """ # noqa: E501
    url: StrictStr
    path: Optional[StrictStr] = None
    on_restart: Literal['preserve changes', 'reclone'] | None = None
    reference: Optional[StrictStr] = None
    reference_type: Literal['branch', 'commit', 'tag'] = 'branch'
    public: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["url", "path", "on_restart", "reference", "reference_type", "public"]

    @field_validator('on_restart')
    def on_restart_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['preserve changes', 'reclone']):
            raise ValueError("must be one of enum values ('preserve changes', 'reclone')")
        return value

    @field_validator('reference_type')
    def reference_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['branch', 'commit', 'tag']):
            raise ValueError("must be one of enum values ('branch', 'commit', 'tag')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalRepoAttachmentRecipe from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reference (nullable) is None
        # and model_fields_set contains the field
        if self.reference is None and "reference" in self.model_fields_set:
            _dict['reference'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalRepoAttachmentRecipe from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "path": obj.get("path"),
            "on_restart": obj.get("on_restart"),
            "reference": obj.get("reference"),
            "reference_type": obj.get("reference_type") if obj.get("reference_type") is not None else 'branch',
            "public": obj.get("public") if obj.get("public") is not None else False
        })
        return _obj


