# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict
from typing_extensions import Self

from saturn_api.models.extra_packages_recipe_apt import ExtraPackagesRecipeApt
from saturn_api.models.extra_packages_recipe_conda import ExtraPackagesRecipeConda
from saturn_api.models.extra_packages_recipe_pip import ExtraPackagesRecipePip


class ExtraPackagesRecipe(BaseModel):
    """
    ExtraPackagesRecipe
    """  # noqa: E501

    pip: Optional[ExtraPackagesRecipePip] = None
    conda: Optional[ExtraPackagesRecipeConda] = None
    apt: Optional[ExtraPackagesRecipeApt] = None
    cran: Optional[ExtraPackagesRecipeApt] = None
    remotes: Optional[ExtraPackagesRecipeApt] = None
    bioconductor: Optional[ExtraPackagesRecipeApt] = None
    __properties: ClassVar[List[str]] = ["pip", "conda", "apt", "cran", "remotes", "bioconductor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExtraPackagesRecipe from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pip
        if self.pip:
            _dict["pip"] = self.pip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conda
        if self.conda:
            _dict["conda"] = self.conda.to_dict()
        # override the default output from pydantic by calling `to_dict()` of apt
        if self.apt:
            _dict["apt"] = self.apt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cran
        if self.cran:
            _dict["cran"] = self.cran.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remotes
        if self.remotes:
            _dict["remotes"] = self.remotes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bioconductor
        if self.bioconductor:
            _dict["bioconductor"] = self.bioconductor.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExtraPackagesRecipe from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "pip": (
                    ExtraPackagesRecipePip.from_dict(obj["pip"])
                    if obj.get("pip") is not None
                    else None
                ),
                "conda": (
                    ExtraPackagesRecipeConda.from_dict(obj["conda"])
                    if obj.get("conda") is not None
                    else None
                ),
                "apt": (
                    ExtraPackagesRecipeApt.from_dict(obj["apt"])
                    if obj.get("apt") is not None
                    else None
                ),
                "cran": (
                    ExtraPackagesRecipeApt.from_dict(obj["cran"])
                    if obj.get("cran") is not None
                    else None
                ),
                "remotes": (
                    ExtraPackagesRecipeApt.from_dict(obj["remotes"])
                    if obj.get("remotes") is not None
                    else None
                ),
                "bioconductor": (
                    ExtraPackagesRecipeApt.from_dict(obj["bioconductor"])
                    if obj.get("bioconductor") is not None
                    else None
                ),
            }
        )
        return _obj
