# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing_extensions import Self


class ExtraPackages(BaseModel):
    """
    ExtraPackages
    """  # noqa: E501

    pip: Optional[StrictStr] = None
    as_requirements_txt: Optional[StrictBool] = False
    conda: Optional[StrictStr] = None
    as_environment_yml: Optional[StrictBool] = False
    apt: Optional[StrictStr] = None
    cran: Optional[StrictStr] = None
    remotes: Optional[StrictStr] = None
    bioconductor: Optional[StrictStr] = None
    use_mamba: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = [
        "pip",
        "as_requirements_txt",
        "conda",
        "as_environment_yml",
        "apt",
        "cran",
        "remotes",
        "bioconductor",
        "use_mamba",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExtraPackages from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pip (nullable) is None
        # and model_fields_set contains the field
        if self.pip is None and "pip" in self.model_fields_set:
            _dict["pip"] = None

        # set to None if conda (nullable) is None
        # and model_fields_set contains the field
        if self.conda is None and "conda" in self.model_fields_set:
            _dict["conda"] = None

        # set to None if apt (nullable) is None
        # and model_fields_set contains the field
        if self.apt is None and "apt" in self.model_fields_set:
            _dict["apt"] = None

        # set to None if cran (nullable) is None
        # and model_fields_set contains the field
        if self.cran is None and "cran" in self.model_fields_set:
            _dict["cran"] = None

        # set to None if remotes (nullable) is None
        # and model_fields_set contains the field
        if self.remotes is None and "remotes" in self.model_fields_set:
            _dict["remotes"] = None

        # set to None if bioconductor (nullable) is None
        # and model_fields_set contains the field
        if self.bioconductor is None and "bioconductor" in self.model_fields_set:
            _dict["bioconductor"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExtraPackages from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "pip": obj.get("pip"),
                "as_requirements_txt": (
                    obj.get("as_requirements_txt")
                    if obj.get("as_requirements_txt") is not None
                    else False
                ),
                "conda": obj.get("conda"),
                "as_environment_yml": (
                    obj.get("as_environment_yml")
                    if obj.get("as_environment_yml") is not None
                    else False
                ),
                "apt": obj.get("apt"),
                "cran": obj.get("cran"),
                "remotes": obj.get("remotes"),
                "bioconductor": obj.get("bioconductor"),
                "use_mamba": obj.get("use_mamba") if obj.get("use_mamba") is not None else False,
            }
        )
        return _obj
