# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2026.02.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from saturn_api.models.hardware_type import HardwareType
from saturn_api.models.image_access_level import ImageAccessLevel
from saturn_api.models.owner import Owner
from typing import Literal, Optional, Set
from typing_extensions import Self

class Image(BaseModel):
    """
    Image
    """ # noqa: E501
    id: StrictStr = Field(description="ID of the image.")
    name: StrictStr = Field(description="Name of the image.")
    owner: Owner = Field(description="Owner of the image.")
    description: StrictStr = Field(description="Description of the image.")
    created_at: StrictStr = Field(description="Creation timestamp.")
    hardware_type: HardwareType
    supports: List[StrictStr] = Field(description="Supported features.")
    access: ImageAccessLevel
    is_base: StrictBool = Field(description="True if the image is a base image for builds.")
    is_gpu: StrictBool = Field(description="True if the image support GPU hardware.")
    trusted: StrictBool = Field(description="True if the image belongs to a trusted source.")
    __properties: ClassVar[List[str]] = ["id", "name", "owner", "description", "created_at", "hardware_type", "supports", "access", "is_base", "is_gpu", "trusted"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Image from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "name",
            "owner",
            "description",
            "created_at",
            "supports",
            "is_base",
            "is_gpu",
            "trusted",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Image from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "owner": Owner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "hardware_type": obj.get("hardware_type"),
            "supports": obj.get("supports"),
            "access": obj.get("access"),
            "is_base": obj.get("is_base"),
            "is_gpu": obj.get("is_gpu"),
            "trusted": obj.get("trusted")
        })
        return _obj


