# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.04.01-1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from saturn_api.models.owner import Owner
from typing import Optional, Set
from typing_extensions import Self

class Image(BaseModel):
    """
    Image
    """ # noqa: E501
    owner_id: Optional[StrictStr] = None
    owner_name: Optional[Annotated[str, Field(strict=True)]] = None
    user_id: Optional[StrictStr] = None
    group_id: Optional[StrictStr] = None
    org_id: Optional[StrictStr] = None
    owner: Optional[Owner] = None
    name: StrictStr
    description: Optional[StrictStr] = None
    is_gpu: StrictBool
    supports: Optional[List[StrictStr]] = None
    access: StrictStr
    id: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    is_base: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["owner_id", "owner_name", "user_id", "group_id", "org_id", "owner", "name", "description", "is_gpu", "supports", "access", "id", "created_at", "is_base"]

    @field_validator('owner_name')
    def owner_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?:(?P<org>[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38})\/)?(?P<identity>[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38})$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?P<org>[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38})\/)?(?P<identity>[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38})$/")
        return value

    @field_validator('access')
    def access_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['account', 'org', 'owner']):
            raise ValueError("must be one of enum values ('account', 'org', 'owner')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Image from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "owner",
            "id",
            "created_at",
            "is_base",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict['group_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Image from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "owner_id": obj.get("owner_id"),
            "owner_name": obj.get("owner_name"),
            "user_id": obj.get("user_id"),
            "group_id": obj.get("group_id"),
            "org_id": obj.get("org_id"),
            "owner": Owner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "name": obj.get("name"),
            "description": obj.get("description"),
            "is_gpu": obj.get("is_gpu"),
            "supports": obj.get("supports"),
            "access": obj.get("access"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "is_base": obj.get("is_base")
        })
        return _obj


