# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.10.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ImageAccessLevel(str, Enum):
    """
    ImageAccessLevel
    """

    """
    allowed enum values
    """
    ACCOUNT = 'account'
    ORG = 'org'
    OWNER = 'owner'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ImageAccessLevel from a JSON string"""
        return cls(json.loads(json_str))


