# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.06.01-36
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from saturn_api.models.image_tag_by_id import ImageTagById
from saturn_api.models.image_tag_by_name import ImageTagByName
from saturn_api.models.image_tag_by_uri import ImageTagByUri
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

IMAGETAGREFERENCE_ANY_OF_SCHEMAS = ["ImageTagById", "ImageTagByName", "ImageTagByUri", "str"]

class ImageTagReference(BaseModel):
    """
    ImageTagReference
    """

    # data type: ImageTagById
    anyof_schema_1_validator: Optional[ImageTagById] = None
    # data type: ImageTagByUri
    anyof_schema_2_validator: Optional[ImageTagByUri] = None
    # data type: ImageTagByName
    anyof_schema_3_validator: Optional[ImageTagByName] = None
    # data type: str
    anyof_schema_4_validator: Optional[StrictStr] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ImageTagById, ImageTagByName, ImageTagByUri, str]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ImageTagById", "ImageTagByName", "ImageTagByUri", "str" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ImageTagReference.model_construct()
        error_messages = []
        # validate data type: ImageTagById
        if not isinstance(v, ImageTagById):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageTagById`")
        else:
            return v

        # validate data type: ImageTagByUri
        if not isinstance(v, ImageTagByUri):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageTagByUri`")
        else:
            return v

        # validate data type: ImageTagByName
        if not isinstance(v, ImageTagByName):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageTagByName`")
        else:
            return v

        # validate data type: str
        try:
            instance.anyof_schema_4_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ImageTagReference with anyOf schemas: ImageTagById, ImageTagByName, ImageTagByUri, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ImageTagById] = None
        try:
            instance.actual_instance = ImageTagById.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ImageTagByUri] = None
        try:
            instance.actual_instance = ImageTagByUri.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ImageTagByName] = None
        try:
            instance.actual_instance = ImageTagByName.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.anyof_schema_4_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_4_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ImageTagReference with anyOf schemas: ImageTagById, ImageTagByName, ImageTagByUri, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ImageTagById, ImageTagByName, ImageTagByUri, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


