# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2025.10.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing_extensions import Self

from saturn_api.models.identity_type import IdentityType


class Owner(BaseModel):
    """
    Owner
    """  # noqa: E501

    id: StrictStr
    name: StrictStr
    identity_name: StrictStr
    org_name: StrictStr
    created_at: StrictStr
    org_admin: StrictBool
    org_id: StrictStr
    user_id: Optional[StrictStr] = None
    group_id: Optional[StrictStr] = None
    identity_type: IdentityType
    avatar_url: StrictStr
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "identity_name",
        "org_name",
        "created_at",
        "org_admin",
        "org_id",
        "user_id",
        "group_id",
        "identity_type",
        "avatar_url",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Owner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "name",
                "identity_name",
                "org_name",
                "created_at",
                "org_admin",
                "org_id",
                "user_id",
                "group_id",
                "avatar_url",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict["user_id"] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict["group_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Owner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "identity_name": obj.get("identity_name"),
                "org_name": obj.get("org_name"),
                "created_at": obj.get("created_at"),
                "org_admin": obj.get("org_admin"),
                "org_id": obj.get("org_id"),
                "user_id": obj.get("user_id"),
                "group_id": obj.get("group_id"),
                "identity_type": obj.get("identity_type"),
                "avatar_url": obj.get("avatar_url"),
            }
        )
        return _obj
