# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Dict, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictStr,
    ValidationError,
    field_validator,
)
from typing_extensions import Literal, Self, TypeVar

from saturn_api.models.deployment_recipe import DeploymentRecipe
from saturn_api.models.image_recipe import ImageRecipe
from saturn_api.models.job_recipe import JobRecipe
from saturn_api.models.workspace_recipe import WorkspaceRecipe

RECIPE_ONE_OF_SCHEMAS = ["DeploymentRecipe", "ImageRecipe", "JobRecipe", "WorkspaceRecipe"]

T = TypeVar(
    "T",
    DeploymentRecipe,
    ImageRecipe,
    JobRecipe,
    WorkspaceRecipe,
    default=Union[DeploymentRecipe, ImageRecipe, JobRecipe, WorkspaceRecipe],
)


class Recipe(RootModel[T]):
    """
    Recipe
    """

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    root: T = Field(discriminator="type")

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        return cls.model_validate_json(json_str)

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.root is None:
            return "null"

        return self.model_dump_json()

    def to_dict(self) -> Dict[str, Any]:
        """Returns the dict representation of the actual instance"""
        if self.root is None:
            return None

        if hasattr(self.root, "to_dict") and callable(self.root.to_dict):
            return self.root.to_dict()
        else:
            return self.model_dump()

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
