# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2026.02.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from saturn_api.models.secret_attachment import SecretAttachment
from typing import Literal, Optional, Set
from typing_extensions import Self

class SecretAttachmentList(BaseModel):
    """
    SecretAttachmentList
    """ # noqa: E501
    secret_attachments: List[SecretAttachment] = Field(description="List of secret attachments.")
    prev_key: Optional[StrictStr] = Field(default=None, description="Previous page key.")
    next_key: Optional[StrictStr] = Field(default=None, description="Next page key.")
    __properties: ClassVar[List[str]] = ["secret_attachments", "prev_key", "next_key"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SecretAttachmentList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "secret_attachments",
            "prev_key",
            "next_key",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in secret_attachments (list)
        _items = []
        if self.secret_attachments:
            for _item_secret_attachments in self.secret_attachments:
                if _item_secret_attachments:
                    _items.append(_item_secret_attachments.to_dict())
            _dict['secret_attachments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SecretAttachmentList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "secret_attachments": [SecretAttachment.from_dict(_item) for _item in obj["secret_attachments"]] if obj.get("secret_attachments") is not None else None,
            "prev_key": obj.get("prev_key"),
            "next_key": obj.get("next_key")
        })
        return _obj


