# coding: utf-8

"""
Saturn Cloud

The API for Saturn Cloud.

The version of the OpenAPI document: 2026.02.01
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from saturn_api.models.ssh_private_key import SSHPrivateKey


class SSHPrivateKeyList(BaseModel):
    """
    SSHPrivateKeyList
    """  # noqa: E501

    ssh_private_keys: List[SSHPrivateKey] = Field(description="List of SSH private keys.")
    prev_key: Optional[StrictStr] = Field(default=None, description="Previous page key.")
    next_key: Optional[StrictStr] = Field(default=None, description="Next page key.")
    __properties: ClassVar[List[str]] = ["ssh_private_keys", "prev_key", "next_key"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SSHPrivateKeyList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "ssh_private_keys",
                "prev_key",
                "next_key",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ssh_private_keys (list)
        _items = []
        if self.ssh_private_keys:
            for _item_ssh_private_keys in self.ssh_private_keys:
                if _item_ssh_private_keys:
                    _items.append(_item_ssh_private_keys.to_dict())
            _dict["ssh_private_keys"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SSHPrivateKeyList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "ssh_private_keys": (
                    [SSHPrivateKey.from_dict(_item) for _item in obj["ssh_private_keys"]]
                    if obj.get("ssh_private_keys") is not None
                    else None
                ),
                "prev_key": obj.get("prev_key"),
                "next_key": obj.get("next_key"),
            }
        )
        return _obj
