# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.10.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Literal, Optional, Set
from typing_extensions import Self

class UserUpdate(BaseModel):
    """
    UserUpdate
    """ # noqa: E501
    username: Optional[StrictStr] = None
    full_name: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    is_multiple_ssh_keys: Optional[StrictBool] = None
    active: Optional[StrictBool] = None
    admin: Optional[StrictBool] = None
    locked: Optional[StrictBool] = None
    limits_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["username", "full_name", "email", "is_multiple_ssh_keys", "active", "admin", "locked", "limits_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if limits_id (nullable) is None
        # and model_fields_set contains the field
        if self.limits_id is None and "limits_id" in self.model_fields_set:
            _dict['limits_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "username": obj.get("username"),
            "full_name": obj.get("full_name"),
            "email": obj.get("email"),
            "is_multiple_ssh_keys": obj.get("is_multiple_ssh_keys"),
            "active": obj.get("active"),
            "admin": obj.get("admin"),
            "locked": obj.get("locked"),
            "limits_id": obj.get("limits_id")
        })
        return _obj


