# coding: utf-8

"""
    Saturn Cloud

    The API for Saturn Cloud.

    The version of the OpenAPI document: 2025.10.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from saturn_api.models.condition import Condition
from saturn_api.models.deployment_status import DeploymentStatus
from typing import Literal, Optional, Set
from typing_extensions import Self

class WorkspaceRuntimeSummary(BaseModel):
    """
    WorkspaceRuntimeSummary
    """ # noqa: E501
    name: StrictStr
    namespace: StrictStr
    uid: StrictStr
    controller_uid: Optional[StrictStr]
    controller_kind: Optional[StrictStr]
    labels: Dict[str, StrictStr]
    annotations: Dict[str, StrictStr]
    conditions: List[Condition]
    started_at: Optional[datetime]
    deleted_at: Optional[datetime]
    status: DeploymentStatus
    scale: StrictInt
    running_count: StrictInt
    active_count: StrictInt
    disk_space: StrictStr
    __properties: ClassVar[List[str]] = ["name", "namespace", "uid", "controller_uid", "controller_kind", "labels", "annotations", "conditions", "started_at", "deleted_at", "status", "scale", "running_count", "active_count", "disk_space"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceRuntimeSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "name",
            "namespace",
            "uid",
            "controller_uid",
            "controller_kind",
            "labels",
            "annotations",
            "conditions",
            "started_at",
            "deleted_at",
            "scale",
            "running_count",
            "active_count",
            "disk_space",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item_conditions in self.conditions:
                if _item_conditions:
                    _items.append(_item_conditions.to_dict())
            _dict['conditions'] = _items
        # set to None if controller_uid (nullable) is None
        # and model_fields_set contains the field
        if self.controller_uid is None and "controller_uid" in self.model_fields_set:
            _dict['controller_uid'] = None

        # set to None if controller_kind (nullable) is None
        # and model_fields_set contains the field
        if self.controller_kind is None and "controller_kind" in self.model_fields_set:
            _dict['controller_kind'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceRuntimeSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "uid": obj.get("uid"),
            "controller_uid": obj.get("controller_uid"),
            "controller_kind": obj.get("controller_kind"),
            "labels": obj.get("labels"),
            "annotations": obj.get("annotations"),
            "conditions": [Condition.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "started_at": obj.get("started_at"),
            "deleted_at": obj.get("deleted_at"),
            "status": obj.get("status"),
            "scale": obj.get("scale"),
            "running_count": obj.get("running_count"),
            "active_count": obj.get("active_count"),
            "disk_space": obj.get("disk_space")
        })
        return _obj


